# Generated by Django 4.2.13 on 2024-05-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instructionA', models.CharField(default='', max_length=250)),
                ('instructionB', models.CharField(default='', max_length=250)),
                ('instructionC', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
