# Generated by Django 4.2.13 on 2024-05-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0002_rename_eventtype_instructionsset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Claude_API', models.CharField(default='', max_length=50)),
                ('Open_API', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
