# Generated by Django 4.2.13 on 2024-05-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0003_settingpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingpage',
            old_name='Open_API',
            new_name='OpenAI_API',
        ),
    ]
