# Generated by Django 4.2.13 on 2024-05-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0004_rename_open_api_settingpage_openai_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionsset',
            name='instructionA',
        ),
        migrations.RemoveField(
            model_name='instructionsset',
            name='instructionB',
        ),
        migrations.RemoveField(
            model_name='instructionsset',
            name='instructionC',
        ),
        migrations.AlterField(
            model_name='settingpage',
            name='Claude_API',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=250)),
                ('instruction_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='promptapp.instructionsset')),
            ],
        ),
    ]
