# Generated by Django 4.2.13 on 2024-05-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0006_settingpage_claude_api_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionsTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionThemeRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=250)),
                ('instruction_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructionsTheme', to='promptapp.instructionstheme')),
            ],
        ),
    ]
