# Generated by Django 4.2.13 on 2024-05-31 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0007_instructionstheme_instructionthemerow'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionsThemeRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=250)),
                ('instruction_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructionsThemeRow', to='promptapp.instructionstheme')),
            ],
        ),
        migrations.DeleteModel(
            name='InstructionThemeRow',
        ),
    ]
